@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam groupInheritance 2
package "Finance" <<Rectangle>> {
package "finances" <<Rectangle>> {
class  "{abstract}\nFinanceManager"
class NormalFinanceManager
class RecurringFinanceManager
}

package "entries" <<Rectangle>> {

class "{abstract}\nRecurringEntry"
class RecurringExpense
class RecurringIncome
class "{abstract}\nEntry"
class Income
class Expense
}

RecurringFinanceManager -u-|> "{abstract}\nFinanceManager"
NormalFinanceManager -u-|> "{abstract}\nFinanceManager"

"{abstract}\nRecurringEntry" -u-|> "{abstract}\nEntry"
RecurringIncome -u-|> "{abstract}\nRecurringEntry"
RecurringExpense -u-|> "{abstract}\nRecurringEntry"
Income -u--|> "{abstract}\nEntry"
Expense -u--|> "{abstract}\nEntry"

RecurringFinanceManager ----> "*" RecurringIncome
RecurringFinanceManager ----> "*" RecurringExpense
NormalFinanceManager ----> "*" Income
NormalFinanceManager ----> "*" Expense


}
hide members
@enduml
