@startuml
box Main
Participant ":Duke" as Duke
end box
box Ui
Participant ":Ui" as Ui
end box
box Logic
Participant ":Parser" as Parser
Participant ":ValidityChecker" as Valid
Participant ":AddCommand" as DeleteCommand
end box



box Model
Participant ":NormalFinanceManager" as NormalFinanceManager
Participant ":Entry" as Entry
Participant ":BudgetManager" as Budget
end box

box Storage
Participant ":NormalListDataManager" as NormalListDataManager
end box

activate Duke
Duke -> Parser : parseCommand(userInput)
activate Parser

Parser -> Parser : prepareAddEntry(userInput)
activate Parser
Parser -> Parser : parseInputByTags(userInput)
activate Parser
Parser -> Valid : checkExistenceAndValidityOfTags(parser, userInput)
activate Valid
Valid --> Parser : validTags
deactivate Valid


Parser --> Parser
deactivate Parser
Parser -> Parser : createIncomeObject()

activate Parser
create Entry

Parser -> Entry : create
activate Entry
Entry --> Parser : entry
deactivate Entry
Parser --> Parser : entry
deactivate Parser

create DeleteCommand
Parser -> DeleteCommand : AddCommand(entry)
activate DeleteCommand
DeleteCommand --> Parser : command
deactivate DeleteCommand
Parser --> Parser : command
deactivate Parser
Parser --> Duke : command

deactivate Parser

Duke -> DeleteCommand : execute(...)

activate DeleteCommand
DeleteCommand -> NormalFinanceManager : addEntry(entry)
activate NormalFinanceManager
NormalFinanceManager --> DeleteCommand
deactivate NormalFinanceManager

DeleteCommand -> NormalListDataManager : appendToEntryListTextFile(entry)
activate NormalListDataManager
NormalListDataManager --> DeleteCommand
deactivate NormalListDataManager


DeleteCommand -> Ui : printEntryAdded(entry)

activate Ui
Ui --> DeleteCommand
deactivate Ui
DeleteCommand -> Budget : checkExceedBudget

DeleteCommand --> Duke
deactivate DeleteCommand
destroy DeleteCommand
@enduml