@startuml
!include Style.puml

participant Duke        as duke
participant DataManagerActions as dataManagerActions
participant ExpenseListDataManager as expenseListDataManager
participant CategoryListDataManager as categoryListDataManager

-> duke : run()
activate duke

create dataManagerActions
duke -> dataManagerActions : new DataManagerActions()
activate dataManagerActions
return path : String

duke -> dataManagerActions : printPreviousFileContents (expenseList:ExpenseList)
activate dataManagerActions

dataManagerActions -> expenseListDataManager : loadExpenseListContents (expense:Expense)
activate expenseListDataManager
return

dataManagerActions -> categoryListDataManager : loadCategoryFileContents()
activate categoryListDataManager
return

return

@enduml